app = "jumia-api-scraping"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  MONGO_URI = "mongodb+srv://moufidzakaria92_db_user:Moufid567Img%24@cluster0.mipcfte.mongodb.net/jumia?retryWrites=true&w=majority"
  MY_KEY = "ta_clef_rapide"
  REDIS_URL = "rediss://default:AWSPAAIncDJhZjcwZmNmNWZkNGQ0MWQyYjhhNTVhYjlhODNlZTU1NnAyMjU3NDM@sure-ostrich-25743.upstash.io:6379"
