app = "jumia-api-scraping"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4001"
  MONGO_URI = "mongodb+srv://...:...@cluster0.mipcfte.mongodb.net/jumia?retryWrites=true&w=majority"
  MY_KEY = "ta_clef_rapide"
  REDIS_URL = "rediss://default:...@sure-ostrich-25743.upstash.io:6379"
