services:
  - type: web
    name: jumia-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npx tsx src/main.ts"   # pour TypeScript direct sans compiler
    autoDeploy: true
